# Generated by Django 3.2 on 2022-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_date_created_productscollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
