# Generated by Django 3.2 on 2022-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['product']},
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='wish_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_products', to='store.customerwishlist'),
        ),
    ]
