# Generated by Django 4.0.6 on 2022-08-23 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220822_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwishlist',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(help_text='product image address', max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='This is the name of the product', max_length=200, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Any positive integer number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique product identification number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trader',
            field=models.ForeignKey(help_text='product merchant', on_delete=django.db.models.deletion.CASCADE, related_name='trader_products', to='main.trader'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
