# Generated by Django 4.0.6 on 2022-08-23 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customerwishlist_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(help_text='product image address', max_length=3000, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique product identification number', verbose_name='product uuid'),
        ),
    ]
