# Generated by Django 4.0 on 2022-08-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cart_product_cart_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
