# Generated by Django 4.0.6 on 2022-08-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategory_alter_product_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
            preserve_default=False,
        ),
    ]
